replicaCount: 2

image:
  repository: gcr.io/june-api-455423/june-api
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - name: gcr-pull-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  ginMode: "release"
  serverPort: "8080"
  apiBaseUrl: ""
  db:
    host: ""
    port: "5432"
    user: ""
    name: ""
    sslMode: "disable"
  jwt:
    accessExpMinutes: "15"
    refreshExpDays: "7"

secrets:
  create: false
  existingSecret: ""
  dbPassword: ""
  jwtAccessSecret: ""
  jwtRefreshSecret: ""

postgresql:
  enabled: false
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  auth:
    username: june_user
    database: june_db
  service:
    port: 5432
  persistence:
    enabled: true
    size: 1Gi

migrations:
  enabled: false
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  image:
    repository: june-api-migrations
    tag: dev
    pullPolicy: IfNotPresent

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
