replicaCount: 2

image:
  repository: gcr.io/june-api-455423/june-api
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - name: gcr-pull-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

config:
  ginMode: "release"
  port: "8080"

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10 