replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

simulation:
  enabled: true
  profile: cpu-saturation
  cpuBurnMs: "250"

loadgen:
  enabled: true
  requests: 700
  workers: 12

