name: Build and Deploy to GKE with Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: your-cluster-name
  GKE_ZONE: your-cluster-zone
  IMAGE: your-image-name
  HELM_RELEASE: your-helm-release
  HELM_CHART: helm/go-api  # path to your Helm chart

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: "gke-gcloud-auth-plugin"

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build -t "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" .

    - name: Push Docker Image to GCR
      run: |
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    - name: Set Up Kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Install Helm CLI
      uses: azure/setup-helm@v4

    - name: Deploy with Helm
      run: |
        helm upgrade --install $HELM_RELEASE $HELM_CHART \
          --set image.repository=gcr.io/$PROJECT_ID/$IMAGE \
          --set image.tag=$GITHUB_SHA \
          --namespace default \
          --create-namespace
