name: Build and Deploy to GKE with Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: june-api-1
  GKE_ZONE: europe-west3
  IMAGE: june-api
  HELM_RELEASE: june-api
  HELM_CHART: helm/june-api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: "gke-gcloud-auth-plugin"

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}
          gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set Image Tag
      id: tag
      run: echo "tag=latest" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: "gke-gcloud-auth-plugin"

    - name: Set Up Kubectl
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Install Helm CLI
      uses: azure/setup-helm@v4

    - name: Deploy with Helm
      run: |
        helm upgrade --install $HELM_RELEASE $HELM_CHART \
          --set image.repository=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }} \
          --set image.tag=${{ needs.build.outputs.image_tag }} \
          --set image.pullSecrets[0].name=gcr-pull-secret \
          --namespace default \
          --create-namespace
